name: copy-secrets
author: gendloop
description: 'Copy secrets'
inputs:
# Required
  repo:
    description: 'Repo Name (e.g. MyRepo)'
    required: true
    default: ''
# Optional
  team:
    description: 'Team Name'
    required: false
    default: ''
  sercret_names:
    description: 'Secret Names (e.g. SECRET1,SECRET2)'
    required: false
    default: 'GENDLOOP_ACCESS_TOKEN'
  sercret_values:
    description: 'Secret Values (e.g. Value1,Value2)'
    required: false
    default: ${{ secrets.GENDLOOP_ACCESS_TOKEN }}

runs:
  using: 'composite'
  steps:
    - name: copy-secrets
      uses: philips-software/Repo-Secret-Manager@main
        with:
          action: create
          token: ${{ secrets.GENDLOOP_ACCESS_TOKEN }}
          secret-names: ${{ inputs.sercret_names }}
          secret-values: ${{ inputs.secrets.values }}
          repo: ${{ inputs.repo }}
          team: ${{ inputs.team }}