name: copy-secrets
author: gendloop
description: 'Copy secrets'
inputs:
# Required
  repo:
    description: 'Repo Name (e.g. MyRepo)'
    required: true
    default: ''
# Optional
  repo_owner:
    description: 'Repo Owner'
    required: false
    default: ${{ github.repository_owner }}
  token:
    description: 'Personal Token'
    required: true
    default: ''
  secret_names:
    description: 'Secret Names (e.g. SECRET1,SECRET2)'
    required: false
    default: ''
  secret_values:
    description: 'Secret Values (e.g. Value1,Value2)'
    required: false
    default: ''

runs:
  using: 'composite'
  steps:
    - name: check-owner-name
      shell: bash
      run: |
        echo use owner name ${{ inputs.repo_owner }}

    - name: copy-secrets
      uses: philips-software/Repo-Secret-Manager@main
      with:
        action: create
        token: ${{ inputs.token }}
        secret-names: ${{ inputs.secret_names }}
        secret-values: ${{ inputs.secret_values }}
        repo: ${{ inputs.repo }}
        repo_owner: ${{ inputs.repo_owner }}
