name: Copy_Secrets_Org

permissions:
  contents: write
  actions: write

on: 
  workflow_dispatch:
    inputs:
      repo:
        description: 'Repo Name (e.g. MyRepo)'
        required: true
        default: ''
      team:
        description: 'Team Name'
        required: false
        default: 'XiGeoAlgorithm'

jobs:
  copy_secrets_org:
    runs-on: ubuntu-latest
    steps:
      - name: copy-secrets-to-org
        uses: philips-software/Repo-Secret-Manager@main
        with:
          action: create
          token: ${{ inputs.token }}
          secret-names: 'GENDLOOP_ACCESS_TOKEN'
          secret-values: ${{ secrets.GENDLOOP_ACCESS_TOKEN }}
          repo: ${{ inputs.repo }}
          team: ${{ inputs.team }}

      